### ISSUE TITLE
Unable to write to share

### ISSUE THREAD

**Issue by MrSheen123** [Zibbp/Ceres#4]
Hi, Apologies for making an issue for it but could not get a dm to your discord. I am having issues with getting ceres to write to the cifs share I have made, I can write to the share from the terminal on the machine but the docker container when trying to archive a vod, shows up as:
[Nest] 1  - 04/23/2022, 4:15:18 PM   ERROR [FilesService] Error creating folder
[Nest] 1  - 04/23/2022, 4:15:18 PM   ERROR [FilesService] Error: EACCES: permission denied, mkdir '(mount location)'

Is there any special permissions I need to be granting? I tried granting 777 temporarily to that folder but it still did not work.

**Comment by Zibbp** [comment]
On the host that has the share mounted I have the following permissions set for the share folder.
```
drwxr-xr-x 2 root root
```
Could you exec into the Ceres container and list the permissions for the mounted share folder?

**Comment by MrSheen123** [comment]
My knowledge with containers and linux is somewhat not great unfortunately and could not find a way to see the permissions that folder has

**Comment by MrSheen123** [comment]
Apologies, got it, I have this on the container folder for vods
drwxr-xr-x    4 root     root          4096 Apr 13 21:25 vods

**Comment by Zibbp** [comment]
The Ceres container by default runs as user `node` so you will have to give permissions to that `node` user to your share folder on the host server. Or you could run the container as root by adding `user: 0:0` to your docker compose file. Below is a snippet of the compose file.
```
    volumes:
      - /mnt/vault/vods:/mnt/vods
      - ./logs:/logs
    ports:
      - 3950:3000
    user: 0:0
```

**Comment by MrSheen123** [comment]
Ayyyy that worked! Running the container as root got the permissions right, I have set a vod to archive and will see if it works!

**Comment by MrSheen123** [comment]
When setting an item away with the container running as root, it works but does not create the required folders or files and setting a second away caused it to crash.
Might be permissions based still as I set it to run from user: 0:0 with an nfs share and it crashed but setting it to a cifs share got me as far as above

**Comment by Zibbp** [comment]
Hmm, I've only ever used a cifs share. Have not tried an NFS share. I'll have to to do some research.

**Comment by MrSheen123** [comment]
That's fair, cifs share would be preferred for files to keep things simple as SMB shares are my primary use case

**Comment by Zibbp** [comment]
CIFS is recommended but NFS will work with some user configurations. Closing.
