### ISSUE TITLE
Error fetching live channels to watch

### ISSUE THREAD

**Issue by andymcblane** [Zibbp/Ceres#6]
Hi there, 

Running into this error "Error fetching live channels to watch" when hitting `/admin/live` 

![image](https://user-images.githubusercontent.com/3156198/167109686-34db0aad-3de0-4c0c-9b8e-7e62719a8a0a.png)

Can't see any relevant logs in any of the services either. 

Thank you :-)

**Comment by andymcblane** [comment]
Had a look around, rest of the API seems fine, just `live` not working

**Comment by Zibbp** [comment]
Hi,

Can you ensure the Ceres container is using the `:latest` tag and pull down the latest release? I suspect this being an issue where the 0.0.6 release (which added the `/live` endpoint) was not properly being pushed to the container registry.

**Comment by andymcblane** [comment]
Thank you, I had tried pulling, so unsure if I just needed to try again or if the version bump resolved it.
