### ISSUE TITLE
Rendering freeze or end with error when stream stop and restart a few seconds later

### ISSUE THREAD

**Issue by soleny894** [Zibbp/Ceres#9]
Hi,

It seems that ceres don't work properly when a stream end and restart a few seconds later. I got the issue a few times where rendering just stop and freeze.

First stream end:
```
Log: REDACTED_live_chat_render.log

    [STATUS] - Fetching Chat Badges 
```

Stream restart a few seconds later:
```
     Streamlink live video REDACTED exited.
    error: No playable streams found on this URL: twitch.tv/REDACTED
    [cli][info] Found matching plugin twitch for URL twitch.tv/REDACTED 
```

Note: Both queue have the same ID.

Maybe you can add a way to restart the rendering manually or don't stop it if the stream restart. Maybe a greater timeout could fix that too I don't know.

**Comment by Zibbp** [comment]
Hi, Here is a quick explanation of how the live stream archiving works.

If a stream were to abruptly stop it would take ~10 seconds for Ceres to detect that the stream is no longer live as it cannot find video stream fragments. At this time it will also stop the chat download and begin the chat render. At this point Ceres will then wait 5 minutes before checking if the stream is live.

Could you help me understand what happened with your stream? Did the stream stop and within ~10 seconds start up again? If that is the case I'm going to guess that it happened in an odd time between Ceres not finding video stream fragments but the stream restarted quick enough for Twitch to not issue a new stream ID which would be why both queue items have the same ID.

If you have the `/logs` volume mounted, could you upload the logs relating to the issue?

**Comment by soleny894** [comment]
Hi,

For the details, sometime streams end instantly (internet problem, power outage etc...) and then after a few seconds (I would say between 5 and 10 seconds) the stream goes up again. Ceres consider it's the same VOD ID but create 2 separate items in queue. The first one is frozen on emote or sometime on badge (no rendering in log) then the other one is stuck saying it can't find any stream. 

-> I also forgot to add that I changed the stream live variable to 1 minute since 5 was too big.

For the logs, here's what I have for the specific VOD:

```
Input #0, mpegts, from '/tmp/REDACTED.ts':
  Duration: 00:40:54.87, start: 101.320000, bitrate: 1978 kb/s
  Program 1 
    Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 130 kb/s
    Stream #0:1[0x101]: Video: h264 (Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive), 1280x720, 30 fps, 30 tbr, 90k tbn, 180k tbc
    Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to '/tmp/REDACTED_video.mp4':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive), 1280x720, q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 130 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=73612 fps=50967 q=-1.0 Lsize=  561679kB time=00:40:54.89 bitrate=1874.3kbits/s speed=1.7e+03x    
video:520689kB audio:39083kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.340688%
ffmpeg exited with code 0
Fetching video duration...
Video duration: 2454
Moving video to /mnt/vods/REDACTED/[...]492/[...]492_video.mp4 ...
Video moved to /mnt/vods/REDACTED/[...]492/[...]492_video.mp4
Deleting Streamlink stream .ts file ...
```
File "moved" but is still "pending" on Ceres interface:
![2022-06-21](https://user-images.githubusercontent.com/105172030/174911422-72712ecc-4693-4373-b08b-c1178608f499.png)


When I force the url with the VOD ID, I can watch the first part of the stream (before it ended instantly) but the chat didn't render (black area), then the second queue item (when stream restart) is giving an error like "error: No playable streams found on this URL" and is stuck until I manually delete it.

**Comment by Zibbp** [comment]
When the chat render is saying "Fetching Emotes or Badges" that can take awhile (upwards of 10 minutes) so it *could* be still working. Are you comfortable with uploading the chat `.json` file or emailing it to me (found on my profile) so I can take a look at it?

As for the "processing" red bar in Ceres that is because the chat is still being rendered, or at least trying to be rendered. As a temporary fix, you can go to the Admin page, edit the VOD in question and set "Is Downloading" to false.
![image](https://user-images.githubusercontent.com/21207065/174917074-06dd12d7-3daa-4f06-afb6-730bf8b67df9.png)

The stream going down and going back up and Twitch not issuing a new Stream ID is the real issue here because the VODs are stored in the database using the stream ID supplied from Twitch. It will error if there is a duplicate. It will also overwrite the previous files saved as they are under the same stream id folder.

Can you supply a snippet of the 2nd stream's log, the one that says "No playable streams found on this URL"?

Finally, this is a long shot and probably won't happen, but Twitch has a "disconnect prevention" feature that will keep the stream running for 90 seconds if a disconnect should happen. If the streamer were to turn this on it would fix the issue, I know that this probably isn't feasible though.
![image](https://user-images.githubusercontent.com/21207065/174918660-b886db2f-827a-44bb-90ae-06193cb47ca2.png)

**Comment by soleny894** [comment]
Hi again,

Sorry for the delay, I was busy with other things.

The video does work but chat don't, for the simple reason that there's nothing to render (no one chatted) so it crashed (maybe a check is needed in case no chat exist -> skip step + Make video available by turning "Is Downloading" to false?).

> Can you supply a snippet of the 2nd stream's log, the one that says "No playable streams found on this URL"?

Unfortunately there's no log for this, it just say that it exited like the second block of my main post show.

>Finally, this is a long shot and probably won't happen, but Twitch has a "disconnect prevention" feature that will keep the stream running for 90 seconds if a disconnect should happen. If the streamer were to turn this on it would fix the issue, I know that this probably isn't feasible though.

Yes I'm aware of this feature but no way I can force streamers to enable that only for me.

I don't really know how Ceres works with the checking delay (one minute for me), but maybe adding a delay before rendering can fix the whole thing, for example it could wait 2/3 minutes before ending the live downloading state so it can restart the downloading process if the VODID is the same or send it to the render step if stream don't come up again.

**Comment by Zibbp** [comment]
> I don't really know how Ceres works with the checking delay (one minute for me), but maybe adding a delay before rendering can fix the whole thing, for example it could wait 2/3 minutes before ending the live downloading state so it can restart the downloading process if the VODID is the same or send it to the render step if stream don't come up again.

With how the current database is setup this is not possible without a significant amount of work which I don't want to put into to Ceres while I'm working on the Golang rewrite. Another issue with that is if the stream does start back up, there are two videos, two chats under the same stream ID. This is something I could implement a fix for in the rewrite.

**Comment by soleny894** [comment]
> This is something I could implement a fix for in the rewrite.

Sure, let's implement that in the new version, no need to do extra work on this one. I'll do everything manually until you come up with that new golang version.

**Comment by Zibbp** [comment]
Closing this issue due to the rewrite, Ganymede, being released. Visit the [Ganymede repository](https://github.com/Zibbp/ganymede) for more information.
